name: 🚀 Авто-деплой Marmol House

# 1. ДОБАВЛЕНО: Принудительный перевод внутренних скриптов GitHub на новую версию
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - master # Запуск при пуше в ветку master

jobs:
  web-deploy:
    name: 🏗️ Сборка и загрузка
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Получение кода
        uses: actions/checkout@v4

      - name: 🟢 Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🔨 Сборка проекта
        run: |
          npm ci
          npm run build

      - name: 📂 Загрузка на Hoster.by
        # 2. ИЗМЕНЕНО: Убрана жесткая привязка к версии 4.3.5
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./ 
          # Команда роботу: "Никогда не удаляй и не трогай эти папки на сервере!"
          exclude: |
            api/**
            cgi-bin/**